### ISSUE TITLE
Improper validation of API Gateway v1 events

### ISSUE THREAD

**Issue by christiangaetano** [apollo-server-integrations/apollo-server-integration-aws-lambda#29]
Hey all, congratulations on the v1 release! I'm hugely appreciative of all the work in Apollo 4.0, including the updated integrations and plugins. (Not to mention the much simpler interfaces, in general.)

As the title implies, I'm running into an issue using this integration with a Lambda proxied by API Gateway v1. After migrating my Apollo 3 code to Apollo 4 and switching to this integration, I'm seeing a HTTP 400 with message "Unknown event type" for all requests.

Upon inspecting the event payload, I see that it includes the following: `"version": "1.0"`. (I believe this is expected, even for API Gateway v1. See the [payload format docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html).)

Based on this, it seems like the problem is certainly coming from the `isV1Event()` function in `src/index.ts`:

```typescript
function isV1Event(event: GatewayEvent): event is APIGatewayProxyEvent {
  return !('version' in event);
}
```

Can anyone explain the rationale for not expecting the `version` property in V1 events? If that truly is a possible scenario, the function could still be amended like so:

```typescript
function isV1Event(event: GatewayEvent): event is APIGatewayProxyEvent {
  return !('version' in event) || ('version' in event && event.version === '1.0');
}
```

Curious to hear your thoughts. And if you're accepting PRs, I could definitely open one for this quick fix.

Thank you and great work!

**Comment by christiangaetano** [comment]
Now realizing maybe this stems from the definition of `APIGatewayProxyEvent` in `@types/aws-lambda`. It seems like that is also lacking the `version` property.

**Comment by trevor-scheer** [comment]
Hey @christiangaetano, thanks for opening an issue. You're correct that I was going off the types for this one. Your solution sounds reasonable to me, would you like to open a PR for it?

**Comment by christiangaetano** [comment]
That makes total sense! I'll look into opening an issue with DefinitelyTyped regarding that as well.

In the meantime, I'd be happy to open a PR to fix this here! I should be able to do that today.

Thank you!

**Comment by coltenkrauter** [comment]
I am getting `POST body missing, invalid Content-Type, or JSON object has no keys` - Did you get it resolved?
