### ISSUE TITLE
Header key is case sensitive when inspecting content-type

### ISSUE THREAD

**Issue by christiangaetano** [apollo-server-integrations/apollo-server-integration-aws-lambda#31]
Hi there, me again! One more small issue that just came up in my testing.

When inspecting the incoming request's `content-type` header to determine how to parse the request body, `headers.get('content-type')` returns `undefined` if the headers are capitalized (e.g., `Content-Type`). In my configuration, the capitalized form seems to be the default for API Gateway. This ultimately causes an empty string to be sent as the body, resulting in this error from Apollo:

```
POST body missing, invalid Content-Type, or JSON object has no keys.
```

It seems like checking for both lowercase and capitalized versions of the header should be the simple fix. I'd be happy to open a small PR for this one as well.

Thanks!

**Comment by trevor-scheer** [comment]
Thanks for filing the PR!
