### ISSUE TITLE
Set CORS headers

### ISSUE THREAD

**Issue by glasser** [apollo-server-integrations/apollo-server-integration-aws-lambda#39]
Because the handler exposed by this package is not a modular piece of middleware, it probably makes sense for it to function like `startStandaloneServer` and have the default behavior of setting `access-control-allow-origin: *` and friends.  (Then potentially layer some mechanism for CORS configuration on top of that, or just tell people who need more configuration to do something like #38.)

**Comment by glasser** [comment]
Or is the theory that if you're using API Gateway you would just enable CORS via API Gateway rather than in the function?

**Comment by poad** [comment]
We suspect that this issue is caused by the fact that Apollo Server v4 no longer has an interface to directly link express middleware.

Currently, the cheapest solution is to wrap `startServerAndCreateLambdaHandler(server)` with `Access-Control-Allow-Origin` header instead of directly with the Lambda Handler, as shown below. header?

```typescript
async function handler(event: GatewayEvent, context: Context, callback: Callback<APIGatewayProxyStructuredResultV2 | APIGatewayProxyResult>) {
  const apolloHandler = startServerAndCreateLambdaHandler(server);
  const resp = await apolloHandler(event, context, callback);
  return {
    ...resp,
    headers: {
      ...resp?.headers,
      'Access-Control-Allow-Origin': '*',
    },
  };
}

export default handler;
```

If possible, it would be great if `startServerAndCreateLambdaHandler()` could specify a callback function to customize the response.

**Comment by glasser** [comment]
Yes, though if you enjoyed that interface, you can see #38 for an alternate approach that doesn't use this package (and which is powered by the same package that powered `apollo-server-lambda` in AS3).

**Comment by poad** [comment]
@glasser Thx!

**Comment by BlenderDude** [comment]
You can now use middleware to mutate headers on the way out with v2.0.0! See README for more info!

**Comment by BlenderDude** [comment]
> We suspect that this issue is caused by the fact that Apollo Server v4 no longer has an interface to directly link express middleware.
> 
> Currently, the cheapest solution is to wrap `startServerAndCreateLambdaHandler(server)` with `Access-Control-Allow-Origin` header instead of directly with the Lambda Handler, as shown below. header?
> 
> ```ts
> async function handler(event: GatewayEvent, context: Context, callback: Callback<APIGatewayProxyStructuredResultV2 | APIGatewayProxyResult>) {
>   const apolloHandler = startServerAndCreateLambdaHandler(server);
>   const resp = await apolloHandler(event, context, callback);
>   return {
>     ...resp,
>     headers: {
>       ...resp?.headers,
>       'Access-Control-Allow-Origin': '*',
>     },
>   };
> }
> 
> export default handler;
> ```
> 
> If possible, it would be great if `startServerAndCreateLambdaHandler()` could specify a callback function to customize the response.

@poad 

This "callback function" is now implemented as middlware in the new version!
