### ISSUE TITLE
Charset directive in content-type header is not supported

### ISSUE THREAD

**Issue by thomaswr** [apollo-server-integrations/apollo-server-integration-aws-lambda#58]
According to https://www.rfc-editor.org/rfc/rfc9110.html#name-charset a content-type header might include a charset directive.

If I send a request with a content-type header that includes a charset directive, it responds with BadRequest.

It works properly without the charset directive.

Request
```bash
curl --location --request POST 'http://localhost:4000' \
--header 'Apollo-Require-Preflight: 1' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw '{"query":"...",}'
```

Response:
```json
{
  "errors": [
    {
      "message": "POST body missing, invalid Content-Type, or JSON object has no keys.",
      "extensions": {
        "code": "BAD_REQUEST"
      }
    }
  ]
}
```

**Comment by BlenderDude** [comment]
Fix snuck in here #57 !

**Comment by coyoteecd** [comment]
@BlenderDude could you publish a patch release to npm please? I am also hitting this with requests coming from a .NET-based HttpClient.

**Comment by BlenderDude** [comment]
@coyoteecd Done!
