### ISSUE TITLE
use express context

### ISSUE THREAD

**Issue by Drilmo** [apollo-server-integrations/apollo-server-integration-aws-lambda#59]
Hi, 

I have a federation with user authentication through jwt, in this new integration, I don't know how I can do it:

```javascript
const server = new ApolloServer({
  schema: buildSubgraphSchema({
    typeDefs,
    resolvers,
    csrfPrevention: true,
  }),
  context: ({ express }) => {
    const user = express.req.headers.user
      ? JSON.parse(express.req.headers.user)
      : null;
    console.log("User: " + JSON.stringify(user));
    return { user };
  },
});
```

I can't find the right writing for this part of the code:

```javascript
exports.graphqlHandler = startServerAndCreateLambdaHandler(server);
```

Can you help me ? 

Thank you in advance for the time you will spend to help me.

**Comment by BlenderDude** [comment]
Thanks for reaching out! This seems like code intended for Apollo Server v3. You might want to take a look [here in the migration docs](https://www.apollographql.com/docs/apollo-server/migration/) to understand other changes, but I'm more than happy to help out here! 

To work with the new context functions, you want to build your context within `startServerAndCreateLambdaHandler` instead. There will also be no `express` function as instead the data will be in the `event` property from AWS Lambda

```typescript
const server = new ApolloServer({
  schema: buildSubgraphSchema({
    typeDefs,
    resolvers,
    csrfPrevention: true,
  }),
});

exports.graphqlHandler = startServerAndCreateLambdaHandler(server, {
  context: async ({ event }) => {
    const user = JSON.parse(event.headers.user ?? "null");
    console.log("User: " + JSON.stringify(user));
    return { user };
  }
});

```

**Comment by trevor-scheer** [comment]
Closing as stale, happy to reopen if there's an actual issue here or if @BlenderDude's comment didn't resolve.
