### ISSUE TITLE
AWS API Gateway Base64 payloads not accepted

### ISSUE THREAD

**Issue by jugory** [apollo-server-integrations/apollo-server-integration-aws-lambda#64]
When receiving Base64 payloads from AWS Gateway, triggering the lambda, I am receiving a JSON parsing error.

I've placed a workaround by doing the decoding myself, but would be great if this was supported!

**Comment by BlenderDude** [comment]
Thanks for the note @jugory! I've opened a PR if you want to take a look. Should take `isBase64Encoded` into consideration when body parsing now!
