### ISSUE TITLE
Support for AppSync Lambda Resolver

### ISSUE THREAD

**Issue by horiuchi** [apollo-server-integrations/apollo-server-integration-aws-lambda#70]
I would like to add support for the AppSync Lambda Resolver.

Lambda is called with the following type in AppSync.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda/trigger/appsync-resolver.d.ts#L3-L6

It is possible to implement a resolver without using Appolo. However, I would appreciate it if it could be implemented using the same interface.

Thank you for considering this.

**Comment by BlenderDude** [comment]
Will be supported with #67 which will allow for custom defined handlers

**Comment by BlenderDude** [comment]
#67 is now ready for review if you want to take a look. Look at the README.md updates to see how this might be implemented.

**Comment by horiuchi** [comment]
Thanks for the quick reply.

I have looked at the README for #67.
It certainly looks like it could be handled by creating a custom request handler.
I will try it later.

And I close this issue.
Thank you very much in advance.
