### ISSUE TITLE
createAPIGatewayProxyEventV2RequestHandler() not working properly

### ISSUE THREAD

**Issue by Lucifer0x17** [apollo-server-integrations/apollo-server-integration-aws-lambda#77]
![image](https://user-images.githubusercontent.com/54178328/214434225-f11bbf63-5056-4cb3-876f-5d37f3a6b53e.png)

I am getting the response if I am using createAPIGatewayProxyEventRequestHandler() handler but if I am using V2 handler I am getting statusCode of 400

**Comment by Lucifer0x17** [comment]
Apologies for a messed up screenshot.
Here is a better view
![image](https://user-images.githubusercontent.com/54178328/214434578-2555484d-94b5-4a4b-a8e5-bbd806acdb88.png)

**Comment by mxmcg** [comment]
FYI a PR is opened for this issue on `@as-integrations/aws-lambda`
https://github.com/apollographql/apollo-server/issues/7327#issuecomment-1405083773

**Comment by Lucifer0x17** [comment]
Ohh okay. Thank you so much. I will close the issue then. 
Thanks.
