### ISSUE TITLE
Cannot read property 'method' of undefined

### ISSUE THREAD

**Issue by przemeklach** [apollo-server-integrations/apollo-server-integration-aws-lambda#80]
I have deployed a lambda using the cdk as follows:

```typescript
const helloFunction = new NodejsFunction(this, 'lambda', {
            entry: path.join(__dirname, "lambda.ts"),
            handler: "handler"
        });
        new LambdaRestApi(this, 'apigw', {
            handler: helloFunction,
        });
```
My lambda is based on the example in the readme. 

```typescript
import {ApolloServer} from '@apollo/server';
import {handlers, startServerAndCreateLambdaHandler} from '@as-integrations/aws-lambda';

const typeDefs = #graphql
type Hello {
    value: String
}

type Query {
    hello(name: String): Hello
}

schema {
    query: Query
}

const resolvers = {
    Query: {
        hello: () => 'world',
    },
}

const server = new ApolloServer({
    typeDefs,
    resolvers,
    introspection: true,
})
console.log('###? running lambda')

export const handler = startServerAndCreateLambdaHandler(
    server,
    handlers.createAPIGatewayProxyEventV2RequestHandler(), {
        middleware: [
            async (event) => {
                console.log('###? received event=' + JSON.stringify(event))
            }
        ]
    });
```

When I try to hit it using postman I get the following error:

> Cannot read property 'method' of undefined

The request does appear to get to the lambda because the logging I have in there shows up. I can see the 'running lambda' output as well as the 'event' that gets logged as part of the middleware. 

Something is going wrong inside startServerAndCreateLambdaHandler() and the above error is returned.

**Comment by rodrigomf24** [comment]
I am facing the same error after upgrading to the latest version

**Comment by przemeklach** [comment]
Excellent, createAPIGatewayProxyEventRequestHandler worked. 

This might be getting a bit out of scope here but what about subscriptions? LambdaRestApi() will handle queries and mutations but subscriptions would require a WebSocket API, no? Would subscription clients have to connect to two separate apis? They would first hit the WebSocket API to create the ws connection and then hit the LambdaRestApi to register the subscription along with the socket they are on?

**Comment by BlenderDude** [comment]
If you want lambda to handle queries and mutations, and something else to handle subscriptions (lambda will not support websockets directly), you can set this up in your client code.

You can have `https://abc.xyz/graphql` set for queries and mutations, and `wss://websockets.abc.xyz` set for subscriptions.

Implementation of such a setup would be out-of-scope for this library though as Lambda does not support incoming websockets.

**Comment by BlenderDude** [comment]
If you're looking for pointers though, I recommend looking into AWS Fargate. That setup would look liked `Application Load Balancer -> Target Group -> Fargate`. It is a 24/7 cost, so at that point you may want to consider running queries, mutations, and subscriptions all on one Fargate instance.

If you want further architecture guidance I reccommend stopping by the Apollo GraphQL Discord! https://discord.gg/graphos

**Comment by jerang** [comment]
> Helped you out with a quick edit to add backticks for the code blocks. The main issue is that the REST Api utilizes the V1 style event, and you are calling the library with the V2 style. Update your call to:
> 
> ```ts
> export const handler = startServerAndCreateLambdaHandler(
>     server,
>     handlers.createAPIGatewayProxyEventRequestHandler(),
>     {
>       middleware: [
>         async (event) => {
>           console.log('###? received event=' + JSON.stringify(event))
>         }
>       ]
>   }
> );
> ```
> 
@BlenderDude thanks for pointing this out; this would be helpful to have in the README.
