### ISSUE TITLE
Require Custom Express Middleware for Cookie Authentication

### ISSUE THREAD

**Issue by Nosherwan** [apollo-server-integrations/apollo-server-integration-aws-lambda#83]
Essentially I am running the below code for cookie authorisation in version 3.
I am using custom express middleware for this that uses cookie parser to parse incoming cookies.
Then I use the context function to parse the cookie extract info.
I believe as custom express is not available in the latest version of the Lambda integration package hence this is not possible in version 4.

Am I right?

```ts
import { ApolloServer } from 'apollo-server-lambda';
import { typeDefs } from './type-defs';
import { resolvers } from './resolvers';
import { appKeyOne } from '../lib/config';
import express from 'express';
import cookieParser from 'cookie-parser';

const apolloServer = new ApolloServer({
    typeDefs,
    resolvers,
    context: ({ event, context, express: { req, res } }) => {
        const { headers, signedCookies } = req;
        const cookie: any = JSON.parse(signedCookies.auth);
        if (cookie?.expires_on) {
            console.log('enhanceApolloContext', cookie);
            if (cookie.token) {
            const   decodedToken = Jwt.verify(cookie.token, jwtSecret);
            }        
        }    
    }
,});

export default apolloServer.createHandler({
    expressAppFromMiddleware(middleware) {
        const app = express();
        app.use(cookieParser(appKeyOne));
        app.use(middleware);
        return app;
    },});

```

**Comment by Nosherwan** [comment]
Thankyou @BlenderDude you have answered my question thoroughly.
Yes my sole purpose here is just to read incoming cookies & then sending back cookies as well. I was not aware that the event will contain the headers in the request with the cookies. I thought event was just the Lambda event.

The [serverless-express](https://github.com/vendia/serverless-express) package looks interesting.
I can understand AS4 goals, however my goal is to have code that I can potentially pick up and put on azure or google app engine & have the least amount of dependency on any platform; so essentially loose coupling.

For now I think you have resolved my issue, I will try to switch over to this integration library, if I have issues I will reach out further.

**Comment by BlenderDude** [comment]
@Nosherwan Not currently without hacking into the request object. Can you make that request in a separate issue and I can implement it? Took a quick look and it doesn't seem difficult to implement

**Comment by ezeikel** [comment]
@BlenderDude Looking for a simple way to do this from resolvers too. Seem to be in a similar situation as @Nosherwan  Im moving away from `apollo-server-lambda` and having access to `res`.

Was there ever a separate issue created as suggested above?
